# Generated by Django 4.1.3 on 2022-11-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('rue', models.CharField(max_length=400)),
                ('code_postal', models.FloatField(default=0)),
                ('ville', models.CharField(max_length=200)),
            ],
        ),
    ]
